#!/bin/bash

# pre-create directories for files generated by Cook-and-cut script
mkdir -p {{ cookiecutter.in.avd.repo_name }}/group_vars/
mkdir -p {{ cookiecutter.in.avd.repo_name }}/group_vars/{{ cookiecutter.in.avd.fabric_name }}_ENDPOINTS/